language: ruby
rvm:
- 2.2.0
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
notifications:
  slack: biblereader:ei4aLnw9dYX7wA8dP8do18CQ
deploy:
  provider: heroku
  app: child-sponsorship-api
  api_key:
    secure: mVPABXaDsV5GnJQWLgYtEq6PmnTMk2UjHPaUk7d4JTG55H5G75fCoCj0ps0KfzQOcD9umddkj/GttcPB2OH+B9HPx0iHXRcKm1i8zN8KAzcxMieVtt6AEAaZbB91j6rEvFbbKJSq5hTzze0CAGTutmzgKhaqFFI/fTrYUuVaEJtHq4Twh60EQhQ0Vd5tbd8rCduhAimHgQ9rDYRu6LJXSDl2OKUhvsZvkgt0NAd5KtaXecGkas05UVPaQdW0pHnpdKNk8OIl07t378ZR6vztDUku50Bd57ytv2ik6gAUl/GoQs7Ova2fO6FM5ydLXWAQRPpAp1rgAm+msXGRM2uIgPHjOLWIbKWszwotBPRgj5QurwT1V0Sli246ggIIw28c8xR9FG8US4gXNKEbAG9H/pXgAgrH3KdfLlBeJtU6xyIekF4TbWbXutUPDFtkRngTJTAPAwGNe02ExACfEGup7Bc755cE/v5wmBYlat9jjekPeHisdhunH1CWO/RQvX3aGzxjWQUvZwFaUPYHIvimPxKQHlRphJa9RFGj1UQvVIRHCkiTRg3ja6E5rtcQnGqhVLCaxrGFSMm+7v2OEVZUfmIsCK1krIV25mnTudI8KOdmPAP2O4azrZmhMhHob8JJz2600X/8srKY29flMJStXtcA8ot1ZF+9TlhCncT6IB0=
  on:
    branch: master
script:
- RACK_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake
env:
  global:
    secure: vrl3cpad71buUHg5ggBs9XaHn2c04tXhuyHTuKI/tipXHEsgGCm7+mD7/1mtbX0UURf1AB7Ryi/+LqE5HnExvsVMjVfJ+Lg/B2HM7CCL3nCZAtJ3ArQHJ+8/dPVXh58WLJu3M9OpE3RGzDmiiXNffGLQmQDT3R5myu5YqkC+ZlVD13wFR3QQqmsL7yyhAxNqdvhCyJJT1lnUkG4CRt/xLp0CqpzLsq+p52tAtAmk/rOCTR5RAlqz4PxoQ9TKLkzW+YkhiRrNVZJzaoVy6znDN9BN3ix2IoMpOzrCJHGhQhUMzXldPFFO9FKCxP/cwBzadEHjqy9kqlQjwJy1LqOQUsXi4y5eX/+nYXLhiGT7wVCA9gz5TO/6BXAznaN9Mv8ehYXlXl+uq/u0Lx94q91DmnF5rVBCHTWJ8WfjmuA/MnRRZi+wpiiozwORBbfWrc5vgHVv7BPvhggDnAbB2yGoGl6wbrT7FkUrxTMshQ+64sBfHcEzRKm7MLQ1uSs4NjEKXN6tpj5jRuNBOC3Q4dI8bxuu86vuO8PnHCz5xIcXOpO+MbHLvOT3RAROGwApqCmtMa0JCN8qUXjKNpWwX+auF/SqH7KeGDIWy9/u4JT3PN7l/FFVn8lJpoYaxjE3Caoa1EYSPCP25m7nqNvONUMwVMIWre1zDMWnVsEH30P/lWE=
